parser: babel-eslint

parserOptions:
    ecmaVersion: 2017
    sourceType: module
    ecmaFeatures:
        jsx: true
        impliedStrict: true
        experimentalObjectRestSpread: true

env:
    node: true
    browser: true
    jest: true
    es6: true

plugins:
    - react 
    - react-hooks
    - prettier

extends:
    - eslint:recommended
    - plugin:react/recommended

rules:
    eqeqeq: 2
    quotes:
        - 2
        - single
        - 
            avoidEscape: true
    no-prototype-builtins: "off"
    no-console: 2
    prefer-const:
        - 2
        -
            destructuring: any
    react/display-name: 0
    react/prop-types:
        - 2
        - ignore: [ actions,model ]
    react-hooks/rules-of-hooks: error
    prettier/prettier:
        - error
        - { endOfLine: auto }
        - usePrettierrc: true

settings:
    react:
        pragma: React
        version: 16.12.0

globals:
    CONFIG: false